[package]
name = "rust-password-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.8.1", features = ["tracing"]}
bcrypt = "0.17.0"
dotenvy = "0.15.7"
serde = "1.0.217"
serde_json = "1.0.138"
sqlx = "0.8.3"
tokio = { version = "1.43.0", features = ["full"] }
tokio-postgres = "0.7.13"
tower-http = { version = "0.6.2", features = ["timeout", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = "1.13.1"
