name: Run Tests in Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Rust Tests in Docker
        uses: ./
        with:
          test-command: "cargo test"
