name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test_db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - "6970:5432"
        volumes:
          - pgdata_test:/var/lib/postgresql/data
          - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        options: --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}" --health-timeout=5s --health-start-period=10s --health-retries=5

    steps:
      - name: Ensure permissions for docker/init.sql
        run: |
          sudo chmod -R 755 ./docker
          sudo chown -R $USER:$USER ./docker

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check PostgreSQL logs
        run: docker logs $(docker ps -q --filter "name=test_db")

      - name: Run tests
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          GRACEFUL_SHUTDOWN_TIME: ${{ secrets.GRACEFUL_SHUTDOWN_TIME }}
        run: cargo test --verbose
