name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Start services using Docker Compose
        run: |
          docker-compose -f ./docker/docker-compose.yml up -d  # Adjust the path to your docker-compose.yml
          sleep 10  # Wait for the services (like DB) to initialize

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-

      - name: Run cargo tests
        run: cargo test --all

      - name: Shut down Docker Compose services
        run: docker-compose -f ./docker/docker-compose.yml down
