name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Start services using Docker Compose
        run: |
          docker-compose -f ./docker/docker-compose.yml up -d  # Adjust the path to your docker-compose.yml
          sleep 10  # Wait for the DB to fully initialize

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo tests
        run: cargo test --all

      - name: Shut down Docker Compose services
        run: docker-compose -f ./docker/docker-compose.yml down
